name: create PDF file
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: convert page to pdf
      uses: wei/curl@master
      with:
        args: https\://v2.convertapi.com/convert/web/to/pdf\?download\=attachment\&secret\=nxxvHh9QNfceVIZK\&url\=https%3A%2F%2Ffxu9411.github.io%2Fonline-cv -o cv_en.pdf
    - name: commit PDF to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: generate PDF from master
        branch: master
        file_pattern: cv_en.pdf
